name: Linter pipeline

on:
    push

jobs:
    Clone-repository:
      runs-on: ubuntu-latest
      steps:
        - name: clone repository
          uses: actions/checkout@v3

        - name: setup node
          uses: actions/setup-node/@v3
          with:
            node-version: 18
        
        - name: prepare application
          run: npm install

        - name: linter configuration
          run: npm init @eslint/config
          
        - name: run linter
          run: npm run-script lint


